name: postgres-example
channels:
  - defaults
dependencies:
  - postgresql
  - psycopg2
  - matplotlib
  - postgis
  - gdal
  - pip
  - pip:
    - pandas
    - git+https://github.com/catherinedevlin/ipython-sql.git
